### ISSUE TITLE
Error pops up again

### ISSUE THREAD

**Issue by brexmania123** [ArceusMatt/AlphaHack-v2#16]
Since mcpe and block launcher updated this version of Alpha hack does not work. I was wondering if you can go and fix it. Since i am on my pc right now i cant know what it is by heart. Can you see if you can fix it. Thx
It says this when you try to run it
org.mozilla.javascript.EcmaError: TypeError: Cannot find function split in object 0. (AlphaHack v2.js#965)
	at org.mozilla.javascript.ScriptRuntime.constructError(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.constructError(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.typeError(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.typeError2(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.notFunctionError(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script.getPasses(AlphaHack v2.js:965)
	at script(AlphaHack v2.js:967)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:271)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:196)
	at java.lang.Thread.run(Thread.java:818)

-Brexmania123

**Comment by ArceusMatt** [comment]
I will be fixing this in the future, as of now i can't fix this but i can remove the feature that is causing this.
